### ISSUE TITLE
Information gathering

### ISSUE THREAD

**Issue by mslinn** [jazzband/help#224]
Jannis,

You might have noticed that I mentioned you in the GitHub projects for zappa,  django-haystack and django-machina. I would like to speak with you, if possible. If you are willing, when and how would work best for you?

Thank you,

Mike

[mslinn.com](https://mslinn.com)

**Comment by jezdez** [comment]
Thanks Mike for opening the ticket, I don't have office hours for Jazzband unfortunately since I'm doing this as a volunteer as well. But if you'd like you can schedule a 30 minutes meeting here: https://calendly.com/jezdez

**Comment by jezdez** [comment]
If you have questions already, feel free to ask them here before the meeting of course.

**Comment by mslinn** [comment]
Jannis,

I read https://jazzband.co/about/guidelines and https://jazzband.co/about/faq

I believe that open source without proper sponsorship is unsustainable. A $10 donation does not move the needle. A lot of the problems I experience in open source simply comes down to insufficient funding. Programmers need to be properly paid for their work.

"The purpose of the Jazzband is to help Open Source projects on GitHub share responsibility for software maintenance." That is not the problem the 3 projects I mentioned face. It is possible that Jazzband might not attempt to address financially-related problems.

These are the topics I would like to explore with you during a conversation:

 - Features and benefits for a project and its contributors when joining JazzBand
 - How are product-related decisions made (e.g. determining priorities, developing a roadmap, etc.)?
 - What is the process for an open source project that has become leaderless (or without a strong leader) to join?
 - Have any sponsors have provided sufficient funding to support one or more developers?

I will select a date and time from the calendar.

Best regards,
Mike

**Comment by jezdez** [comment]
> Jannis,
> 
> I read https://jazzband.co/about/guidelines and https://jazzband.co/about/faq
> 
> I believe that open source without proper sponsorship is unsustainable. A $10 donation does not move the needle. A lot of the problems I experience in open source simply comes down to insufficient funding. Programmers need to be properly paid for their work.

Sure, I agree, there is no way around the fact that developers in general deserve being paid for their work. There is a shortage of direct funding for Open Source software compared to the value that is created with it. But there is also a lot of Open Source software being created and maintained by volunteers, who contribute their time for many different reasons. 

> "The purpose of the Jazzband is to help Open Source projects on GitHub share responsibility for software maintenance." That is not the problem the 3 projects I mentioned face.

What *is* the problem those projects face?

> It is possible that Jazzband might not attempt to address financially-related problems.

There are many different ways to read this, so I'm not sure how to answer this completely. But I can generally say that Jazzband hasn't so far provided funding to work on Jazzband projects. It was designed to provide a place for existing projects to find a "neutral ground" to share or hand-over maintenance to new maintainers, and also make it easier to
onboard new ones. But compensation of individual members is simply out-of-scope at the moment given the legal and financial complexities of a global community of volunteers.

As to what the future for Jazzband holds, if Jazzband continues to get proposals to transfer projects, some funds will be needed to off-set infrastructure cost, that's why the [PSF fiscal sponsorship](https://jazzband.co/news/2021/06/04/fiscal-sponsorship) application happened.

> These are the topics I would like to explore with you during a conversation:
> 
>     * Features and benefits for a project and its contributors when joining JazzBand
> 
>     * How are product-related decisions made (e.g. determining priorities, developing a roadmap, etc.)?
>     * What is the process for an open source project that has become leaderless (or without a strong leader) to join?
> 
>     * Have any sponsors have provided sufficient funding to support one or more developers?
> 
> 
> I selected Saturday at 10 AM ET from your calendar.

Oh, that's embarrassing, I had the event type in Calendly misconfigured, we'll need to do this outside the weekend, would you mind rescheduling?

**Comment by hugovk** [comment]
Closing this old issue, can re-open if needed.
