### ISSUE TITLE
How do I remove travis-ci from project?

### ISSUE THREAD

**Issue by brianmay** [jazzband/help#255]
Pull requests are failing because travis is no longer being run. How do I get github to realise this is the new normal?

* https://github.com/jazzband/django-revproxy/pull/127
* https://github.com/jazzband/django-revproxy/pull/128
* https://github.com/jazzband/django-revproxy/pull/130

Why does it think that travis-ci is required? Why is is trying to run codeclimate and pre-commit.ci?

**Comment by hugovk** [comment]
I expect Travis CI is a "required status check" as part of "branch protection rules" for those repos. An admin/roadie will need to go to the `/settings/branches` page and disable them.

For pre-commit, I think it's been enabled as an app for all repos in the Jazzband organisation. The easiest thing to do is a `.pre-commit-config.yaml` file to the repo. (I've just created a PR: https://github.com/jazzband/django-revproxy/pull/132.) Otherwise, perhaps it can be turned off for that one repo.

For codeclimate, I've not used that for a long time. I expect it either needs turning off from the org/repo settings, or perhaps it can be removed at https://codeclimate.com/

**Comment by brianmay** [comment]
OK, I have disabled that option for now. But still surprised it required travis ci and not say pre-commit.ci.

**Comment by hugovk** [comment]
I'm guessing the Travis requirement is a legacy thing from the repo's pre-Jazzband days?

pre-commit.ci is pretty new.

**Comment by brianmay** [comment]
@hugovk Yes, that is correct.

**Comment by brianmay** [comment]
Where does the reference to codeclimate come from? Is that old or new?

**Comment by hugovk** [comment]
Code Climate will be old. For example, the check at https://github.com/jazzband/django-revproxy/pull/128 links to https://codeclimate.com/github/TracyWebTech/django-revproxy/pull/128 and I suppose TracyWebTech was the pre-Jazzband home for the repo?

To remove Code Climate, we should probably ask @jezdez the Jazzband roadie to check the repo/org settings and remove it. Are there any other repos that should have Code Climate removed?

**Comment by brianmay** [comment]
I still have full access to the repo, but don't see any Code Climate references. I am hoping that maybe this only happened because it is an older PR, that probably needs updating.

**Comment by hugovk** [comment]
Does this help? https://docs.codeclimate.com/docs/removing-a-repository

**Comment by brianmay** [comment]
I suspect not, I don't have a codeclimate account. And the problem is on github anyway, for complaining that codeclimate didn't run, because we removed the webwook.
