### ISSUE TITLE
PyPI Release: django-constance

### ISSUE THREAD

**Issue by Natim** [jazzband/help#307]
# PyPI Release

Could you please release django-constance?

Thank you

Refs https://github.com/jazzband/help/issues/306

**Comment by jezdez** [comment]
Fixed via https://github.com/jazzband/django-constance/pull/497.

**Comment by Mogost** [comment]
There are a lot of things https://github.com/jazzband/django-constance/pull/469 here. 
And we really need to consider this PR. I would appreciate any help in reviewing this PR.
@jezdez , your opinion would be especially valuable, since there are supposed to be changed in the code that was originally written by you.
